mv "./AD/bake AD.mp3"	./AD/b_aa_aa_hkesjidh.mp3
mv "./ED/bake ED.mp3"	./ED/b_aa_aa_hkesjidh.mp3
mv "./KB/bake KB.mp3"	./KB/b_aa_aa_hkesjidh.mp3
mv "./AD/brød AD.mp3"	./AD/laejpie.mp3
mv "./ED/brød ED.mp3"	./ED/laejpie.mp3
mv "./KB/brød KB.mp3"	./KB/laejpie.mp3
mv "./AD/bær AD.mp3"	./AD/muerjie.mp3
mv "./ED/bær ED.mp3"	./ED/muerjie.mp3
mv "./KB/bær KB.mp3"	./KB/muerjie.mp3
mv "./AD/drikke AD.mp3"	./AD/jovkedh.mp3
mv "./ED/drikke ED.mp3"	./ED/jovkedh.mp3
mv "./KB/drikke KB.mp3"	./KB/jovkedh.mp3
mv "./AD/duke AD.mp3"	./AD/dealodh.mp3
mv "./ED/duke ED.mp3"	./ED/dealodh.mp3
mv "./AD/egg AD.mp3"	./AD/munnie.mp3
mv "./ED/egg ED.mp3"	./ED/munnie.mp3
mv "./AD/fisk AD.mp3"	./AD/guelie.mp3
mv "./ED/fisk ED.mp3"	./ED/guelie.mp3
mv "./KB/fisk KB.mp3"	./KB/guelie.mp3
mv "./AD/frokost AD.mp3"	./AD/aeredsbeapmoe.mp3
mv "./ED/frokost ED.mp3"	./ED/aeredsbeapmoe.mp3
mv "./KB/frokost KB.mp3"	./KB/aeredsbeapmoe.mp3
mv "./AD/grønnsak AD.mp3"	./AD/kroenesaate.mp3
mv "./ED/grønnsak ED.mp3"	./ED/kroenesaate.mp3
mv "./KB/grønnsak KB.mp3"	./KB/kroenesaate.mp3
mv "./AD/kaffe AD.mp3"	./AD/pr_ii_htjege.mp3
mv "./ED/kaffe ED.mp3"	./ED/pr_ii_htjege.mp3
mv "./KB/kaffe KB.mp3"	./KB/pr_ii_htjege.mp3
mv "./AD/kjøtt AD.mp3"	./AD/bearkoe.mp3
mv "./ED/kjøtt ED.mp3"	./ED/bearkoe.mp3
mv "./KB/kjøtt KB.mp3"	./KB/bearkoe.mp3
mv "./AD/koke AD.mp3"	./AD/doeltedh.mp3
mv "./ED/koke ED.mp3"	./ED/doeltedh.mp3
mv "./KB/koke KB.mp3"	./KB/doeltedh.mp3
mv "./AD/korv AD.mp3"	./AD/goerve.mp3
mv "./ED/korv ED.mp3"	./ED/goerve.mp3
mv "./KB/korv KB.mp3"	./KB/goerve.mp3
mv "./AD/kveldsmat AD.mp3"	./AD/iehkedsbeapmoe.mp3
mv "./ED/kveldsmat ED.mp3"	./ED/iehkedsbeapmoe.mp3
mv "./KB/kveldsmat KB.mp3"	./KB/iehkedsbeapmoe.mp3
mv "./AD/lage mat AD.mp3"	./AD/jurjiehtidh.mp3
mv "./ED/lage mat ED.mp3"	./ED/jurjiehtidh.mp3
mv "./KB/lage mat KB.mp3"	./KB/jurjiehtidh.mp3
mv "./AD/mat AD.mp3"	./AD/beapmoe.mp3
mv "./ED/mat ED.mp3"	./ED/beapmoe.mp3
mv "./KB/mat KB.mp3"	./KB/beapmoe.mp3
mv "./ED/melk ED.mp3"	./ED/mielhkie.mp3
mv "./KB/melk KB.mp3"	./KB/mielhkie.mp3
mv "./AD/middag AD.mp3"	./AD/gaskebiejjiebeapmoe.mp3
mv "./ED/middag ED.mp3"	./ED/gaskebiejjiebeapmoe.mp3
mv "./KB/middag KB.mp3"	./KB/gaskebiejjiebeapmoe.mp3
mv "./AD/ost AD.mp3"	./AD/vuasta.mp3
mv "./ED/ost ED.mp3"	./ED/vuasta.mp3
mv "./KB/ost KB.mp3"	./KB/vuasta.mp3
mv "./AD/potet AD.mp3"	./AD/peara.mp3
mv "./ED/potet ED.mp3"	./ED/peara.mp3
mv "./KB/potet KB.mp3"	./KB/peara.mp3
mv "./ED/saft ED.mp3"	./ED/aaloe.mp3
mv "./KB/saft KB.mp3"	./KB/aaloe.mp3
mv "./AD/smør AD.mp3"	./AD/voeje.mp3
mv "./ED/smør ED.mp3"	./ED/voeje.mp3
mv "./KB/smør KB.mp3"	./KB/voeje.mp3
mv "./AD/spise AD.mp3"	./AD/by_oe_pmedidh.mp3
mv "./ED/spise ED.mp3"	./ED/by_oe_pmedidh.mp3
mv "./KB/spise KB.mp3"	./KB/by_oe_pmedidh.mp3
mv "./AD/steke AD.mp3"	./AD/bissedh.mp3
mv "./ED/steke ED.mp3"	./ED/bissedh.mp3
mv "./AD/suppe AD.mp3"	./AD/joptse.mp3
mv "./ED/suppe ED.mp3"	./ED/joptse.mp3
mv "./KB/suppe KB.mp3"	./KB/joptse.mp3
mv "./AD/takk AD.mp3"	./AD/gudtsien.mp3
mv "./ED/takk ED.mp3"	./ED/gudtsien.mp3
mv "./KB/takk KB.mp3"	./KB/gudtsien.mp3
mv "./AD/vann AD.mp3"	./AD/tjaehtsie.mp3
mv "./ED/vann ED.mp3"	./ED/tjaehtsie.mp3
mv "./KB/vann KB.mp3"	./KB/tjaehtsie.mp3
mv "./AD/værsågod AD.mp3"	./AD/duelie.mp3
mv "./ED/værsågod ED.mp3"	./ED/duelie.mp3
mv "./KB/værsågod KB.mp3"	./KB/duelie.mp3
mv "./ED/øl ED.mp3"	./ED/voelege.mp3
mv "./KB/øl KB.mp3"	./KB/voelege.mp3
