## NB: this key is not actually used in any of the code, but just here
## to document the format.


Examples:
  # Each question is an entry in a list

  # Valid types:
  #   "image_to_word"
  #   "word_to_word"
  #   "word_to_image"
  #
  # These govern how to display items in the interface.
  #
  - type: "image_to_word"

    # A category name which determines what set the questions belong to
    # in the UI.
    #
    category: "FACE"

    # A name for internal uses (this will not be displayed to users)
    #
    name: "Bodypart image to word"

    # The level is essentially the order that the question comes in
    # progression.
    #
    level: 1

    # Number of answers displayed to the user. 1 - 4
    answers: 1

    # Full amount of points awarded. (Points decrease for each second of
    # inactivity)
    #
    points: 50

    # Play a sound if associated with the question concept that is
    # displayed.
    #
    sound: true

    # Filters select question-answer concepts. For now, images are
    # considered to be a separate 'language' in the system for concepts,
    # otherwise standard 3-character ISO codes are needed. If the user's
    # interface language is to be used to generate, use the value
    # "USERLANG".
    #
    # For the semantics setting, use a list of semantic sets that must
    # intersect with concepts in the database.
    #
    # TODO: implement alternate things that may select concepts, such as image
    # tags.
    filters:
      from_language: "img"
      to_language: "sma"
      semantics:
        - "FACE"

    # For all additional answers that will be displayed to "fill in" the
    # answers when the number of answers displayed is greater than one,
    # control how these answers should be filtered. It may be you wish
    # to include some phonetic features to make things more challenging,
    # and these would go here.
    #
    answer_similarity:
      semantics:
        - "FACE"
      # features:
      #   - "BISYL"
      #   - "HT"


# Some of my own shortcuts...

BpImgWord: &FACE_IMG_WORD
  type: "image_to_word"
  category: "FACE"
  name: "Face image to word"

  repetitions: 2
  level: 1
  answers: 1
  points: 50
  sound: true

  filters:
    from_language: "img"
    to_language: "sma"
    semantics:
      - "FACE"

  answer_similarity:
    semantics:
      - "FACE"

BpWordImg: &FACE_WORD_IMG
  type: "word_to_image"
  category: "FACE"
  name: "Face image to word"

  repetitions: 2
  level: 1
  answers: 1
  points: 50
  sound: true

  filters:
    from_language: "sma"
    to_language: "img"
    semantics:
      - "FACE"

  answer_similarity:
    semantics:
      - "FACE"

BodyImgWord: &BODY_IMG_WORD
  type: "image_to_word"
  category: "BODY"
  name: "Body image to word"

  repetitions: 2
  level: 1
  answers: 1
  points: 50
  sound: true

  filters:
    from_language: "img"
    to_language: "sma"
    semantics:
      - "BODY"

  answer_similarity:
    semantics:
      - "BODY"

BodyWordImg: &BODY_WORD_IMG
  type: "word_to_image"
  category: "BODY"
  name: "Body image to word"

  repetitions: 2
  level: 1
  answers: 1
  points: 50
  sound: true

  filters:
    from_language: "sma"
    to_language: "img"
    semantics:
      - "BODY"

  answer_similarity:
    semantics:
      - "BODY"

HouseImgWord: &HOUSE_IMG_WORD
  type: "image_to_word"
  category: "HOUSE"
  name: "House image to word"

  repetitions: 2
  level: 1
  answers: 1
  points: 50
  sound: true

  filters:
    from_language: "img"
    to_language: "sma"
    semantics:
      - "HOUSE"

  answer_similarity:
    semantics:
      - "HOUSE"

HouseWordImg: &HOUSE_WORD_IMG
  type: "word_to_image"
  category: "HOUSE"
  name: "House image to word"

  repetitions: 2
  level: 1
  answers: 1
  points: 50
  sound: true

  filters:
    from_language: "sma"
    to_language: "img"
    semantics:
      - "HOUSE"

  answer_similarity:
    semantics:
      - "HOUSE"

NumbersImgWord: &NUMBERS_IMG_WORD
  type: "image_to_word"
  category: "NUMBERS"
  name: "Numbers image to word"

  repetitions: 2
  level: 1
  answers: 1
  points: 50
  sound: true

  filters:
    from_language: "img"
    to_language: "sma"
    semantics:
      - "NUMBERS"

  answer_similarity:
    semantics:
      - "NUMBERS"

NumbersWordImg: &NUMBERS_WORD_IMG
  type: "word_to_image"
  category: "NUMBERS"
  name: "Numbers image to word"

  repetitions: 2
  level: 1
  answers: 1
  points: 50
  sound: true

  filters:
    from_language: "sma"
    to_language: "img"
    semantics:
      - "NUMBERS"

  answer_similarity:
    semantics:
      - "NUMBERS"

TimeImgWord: &TIME_IMG_WORD
  type: "image_to_word"
  category: "TIME"
  name: "Time image to word"

  repetitions: 2
  level: 1
  answers: 1
  points: 50
  sound: true

  filters:
    from_language: "img"
    to_language: "sma"
    semantics:
      - "TIME"

  answer_similarity:
    semantics:
      - "TIME"

TimeWordImg: &TIME_WORD_IMG
  type: "word_to_image"
  category: "TIME"
  name: "Time image to word"

  repetitions: 2
  level: 1
  answers: 1
  points: 50
  sound: true

  filters:
    from_language: "sma"
    to_language: "img"
    semantics:
      - "TIME"

  answer_similarity:
    semantics:
      - "TIME"

DefaultImgWord: &DEFAULT_IMG_WORD
  type: "image_to_word"
  category: "DEFAULTS"
  name: "Default image to word"

  repetitions: 2
  level: 1
  answers: 1
  points: 50
  sound: true

  filters:
    from_language: "img"
    to_language: "sma"
    semantics: False

  answer_similarity:
    semantics: False

DefaultWordImg: &DEFAULT_WORD_IMG
  type: "word_to_image"
  category: "DEFAULTS"
  name: "Default image to word"

  repetitions: 2
  level: 1
  answers: 1
  points: 50
  sound: true

  filters:
    from_language: "sma"
    to_language: "img"
    semantics: False

  answer_similarity:
    semantics: False

GreetingImgWord: &GREETING_IMG_WORD
  type: "image_to_word"
  category: "GREETINGS"
  name: "Greetings image to word"

  repetitions: 2
  level: 1
  answers: 1
  points: 50
  sound: true

  filters:
    from_language: "img"
    to_language: "sma"
    semantics:
      - "GREETINGS"

  answer_similarity:
    semantics:
      - "GREETINGS"

GreetingWordImg: &GREETING_WORD_IMG
  type: "word_to_image"
  category: "GREETINGS"
  name: "Greetings image to word"

  repetitions: 2
  level: 1
  answers: 1
  points: 50
  sound: true

  filters:
    from_language: "sma"
    to_language: "img"
    semantics:
      - "GREETINGS"

  answer_similarity:
    semantics:
      - "GREETINGS"

PhrasesImgWord: &PHRASES_IMG_WORD
  type: "image_to_word"
  category: "PHRASES"
  name: "Phrasess image to word"

  repetitions: 2
  level: 1
  answers: 1
  points: 50
  sound: true

  filters:
    from_language: "img"
    to_language: "sma"
    semantics:
      - "PHRASE"

  answer_similarity:
    semantics:
      - "PHRASE"

PhrasesWordImg: &PHRASES_WORD_IMG
  type: "word_to_image"
  category: "PHRASES"
  name: "Phrasess image to word"

  repetitions: 2
  level: 1
  answers: 1
  points: 50
  sound: true

  filters:
    from_language: "sma"
    to_language: "img"
    semantics:
      - "PHRASE"

  answer_similarity:
    semantics:
      - "PHRASE"

FoodImgWord: &FOOD_IMG_WORD
  type: "image_to_word"
  category: "FOOD"
  name: "Food image to word"

  repetitions: 2
  level: 1
  answers: 1
  points: 50
  sound: true

  filters:
    from_language: "img"
    to_language: "sma"
    semantics:
      - "FOOD"

  answer_similarity:
    semantics:
      - "FOOD"

FoodWordImg: &FOOD_WORD_IMG
  type: "word_to_image"
  category: "FOOD"
  name: "Food image to word"

  repetitions: 2
  level: 1
  answers: 1
  points: 50
  sound: true

  filters:
    from_language: "sma"
    to_language: "img"
    semantics:
      - "FOOD"

  answer_similarity:
    semantics:
      - "FOOD"

AnimalsImgWord: &ANIMALS_IMG_WORD
  type: "image_to_word"
  category: "ANIMALS"
  name: "Animals image to word"

  repetitions: 2
  level: 1
  answers: 1
  points: 50
  sound: true

  filters:
    from_language: "img"
    to_language: "sma"
    semantics:
      - "ANIMALS"

  answer_similarity:
    semantics:
      - "ANIMALS"

AnimalsWordImg: &ANIMALS_WORD_IMG
  type: "word_to_image"
  category: "ANIMALS"
  name: "Animals image to word"

  repetitions: 2
  level: 1
  answers: 1
  points: 50
  sound: true

  filters:
    from_language: "sma"
    to_language: "img"
    semantics:
      - "ANIMALS"

  answer_similarity:
    semantics:
      - "ANIMALS"

WorldImgWord: &WORLD_IMG_WORD
  type: "image_to_word"
  category: "WORLD"
  name: "World image to word"

  repetitions: 2
  level: 1
  answers: 1
  points: 50
  sound: true

  filters:
    from_language: "img"
    to_language: "sma"
    semantics:
      - "WORLD"

  answer_similarity:
    semantics:
      - "WORLD"

WorldWordImg: &WORLD_WORD_IMG
  type: "word_to_image"
  category: "WORLD"
  name: "World image to word"

  repetitions: 2
  level: 1
  answers: 1
  points: 50
  sound: true

  filters:
    from_language: "sma"
    to_language: "img"
    semantics:
      - "WORLD"

  answer_similarity:
    semantics:
      - "WORLD"

# For category definitions, see categories.yaml.

Questions:
  # -*- face -*- 
  
  - <<: *FACE_IMG_WORD

  - <<: *FACE_WORD_IMG
    level: 2
    answers: 2
    points: 50

  - <<: *FACE_WORD_IMG
    level: 3
    answers: 3
    points: 50

  - <<: *FACE_WORD_IMG
    level: 4
    answers: 4
    points: 50

  # -*- body -*- 
  
  - <<: *BODY_IMG_WORD

  - <<: *BODY_WORD_IMG
    level: 2
    answers: 2
    points: 50

  - <<: *BODY_WORD_IMG
    level: 3
    answers: 3
    points: 50

  - <<: *BODY_WORD_IMG
    level: 4
    answers: 4
    points: 50

  # -*- house -*- 
  
  - <<: *HOUSE_IMG_WORD

  - <<: *HOUSE_WORD_IMG
    level: 2
    answers: 2
    points: 50

  - <<: *HOUSE_WORD_IMG
    level: 3
    answers: 3
    points: 50

  - <<: *HOUSE_WORD_IMG
    level: 4
    answers: 4
    points: 50

  # -*- numbers -*- 
  
  - <<: *NUMBERS_IMG_WORD

  - <<: *NUMBERS_WORD_IMG
    level: 2
    answers: 2
    points: 50

  - <<: *NUMBERS_WORD_IMG
    level: 3
    answers: 3
    points: 50

  - <<: *NUMBERS_WORD_IMG
    level: 4
    answers: 4
    points: 50

  # -*- time -*- 
  
  - <<: *TIME_IMG_WORD

  - <<: *TIME_WORD_IMG
    level: 2
    answers: 2
    points: 50

  - <<: *TIME_WORD_IMG
    level: 3
    answers: 3
    points: 50

  - <<: *TIME_WORD_IMG
    level: 4
    answers: 4
    points: 50


  # -*- default -*- 

  - <<: *DEFAULT_IMG_WORD

  - <<: *DEFAULT_WORD_IMG
    level: 2
    answers: 2
    points: 50

  - <<: *DEFAULT_WORD_IMG
    level: 3
    answers: 3
    points: 50

  - <<: *DEFAULT_WORD_IMG
    level: 4
    answers: 4
    points: 50


  # -*- heelsedh -*- 

  - <<: *GREETING_IMG_WORD

  - <<: *GREETING_WORD_IMG
    level: 2
    answers: 2
    points: 50

  - <<: *GREETING_WORD_IMG
    level: 3
    answers: 3
    points: 50

  - <<: *GREETING_WORD_IMG
    level: 4
    answers: 4
    points: 50
 
  # -*- heelsedh -*- 

  - <<: *PHRASES_IMG_WORD

  - <<: *PHRASES_WORD_IMG
    level: 2
    answers: 2
    points: 50

  - <<: *PHRASES_WORD_IMG
    level: 3
    answers: 3
    points: 50

  - <<: *PHRASES_WORD_IMG
    level: 4
    answers: 4
    points: 50

  # -*- food -*- 

  - <<: *FOOD_IMG_WORD

  - <<: *FOOD_WORD_IMG
    level: 2
    answers: 2
    points: 50

  - <<: *FOOD_WORD_IMG
    level: 3
    answers: 3
    points: 50

  - <<: *FOOD_WORD_IMG
    level: 4
    answers: 4
    points: 50

  # -*- nature-world -*- 

  - <<: *WORLD_IMG_WORD

  - <<: *WORLD_WORD_IMG
    level: 2
    answers: 2
    points: 50

  - <<: *WORLD_WORD_IMG
    level: 3
    answers: 3
    points: 50

  - <<: *WORLD_WORD_IMG
    level: 4
    answers: 4
    points: 50

  # -*- nature-animals -*- 

  - <<: *ANIMALS_IMG_WORD

  - <<: *ANIMALS_WORD_IMG
    level: 2
    answers: 2
    points: 50

  - <<: *ANIMALS_WORD_IMG
    level: 3
    answers: 3
    points: 50

  - <<: *ANIMALS_WORD_IMG
    level: 4
    answers: 4
    points: 50

  # -*- test -*-
  - type: "image_to_word"
    category: "TEST"
    name: "Bodypart image to word"

    level: 1
    answers: 1
    points: 50
    sound: true
    repetitions: 1

    filters:
      from_language: "img"
      to_language: "sma"
      semantics:
        - "NUMBER_TEST"

    answer_similarity:
      semantics:
        - "NUMBER_TEST"

  - type: "word_to_image"
    category: "TEST"
    name: "Bodypart image to word"

    level: 2
    answers: 3
    points: 50
    sound: true
    repetitions: 0

    filters:
      from_language: "sma"
      to_language: "img"
      semantics:
        - "NUMBER_TEST"

    answer_similarity:
      semantics:
        - "NUMBER_TEST"

  - type: "word_to_image"
    category: "TEST"
    name: "Bodypart image to word"

    level: 3
    answers: 3
    points: 50
    sound: true
    repetitions: 1

    filters:
      from_language: "sma"
      to_language: "img"
      semantics:
        - "NUMBER_TEST"

    answer_similarity:
      semantics:
        - "NUMBER_TEST"
