## NB: this key is not actually used in any of the code, but just here
## to document the format.


Examples:
  # Each question is an entry in a list

  # Valid types:
  #   "image_to_word"
  #   "word_to_word"
  #   "word_to_image"
  #
  # These govern how to display items in the interface.
  #
  - type: "image_to_word"

    # A category name which determines what set the questions belong to
    # in the UI.
    #
    category: "FACE"

    # A name for internal uses (this will not be displayed to users)
    #
    name: "Bodypart image to word"

    # The level is essentially the order that the question comes in
    # progression.
    #
    level: 1

    # Number of answers displayed to the user. 1 - 4
    answers: 1

    # Full amount of points awarded. (Points decrease for each second of
    # inactivity)
    #
    points: 50

    # Play a sound if associated with the question concept that is
    # displayed.
    #
    sound: true

    # Filters select question-answer concepts. For now, images are
    # considered to be a separate 'language' in the system for concepts,
    # otherwise standard 3-character ISO codes are needed. If the user's
    # interface language is to be used to generate, use the value
    # "USERLANG".
    #
    # For the semantics setting, use a list of semantic sets that must
    # intersect with concepts in the database.
    #
    # TODO: implement alternate things that may select concepts, such as image
    # tags.
    filters:
      from_language: "img"
      to_language: "sma"
      semantics:
        - "FACE"

    # For all additional answers that will be displayed to "fill in" the
    # answers when the number of answers displayed is greater than one,
    # control how these answers should be filtered. It may be you wish
    # to include some phonetic features to make things more challenging,
    # and these would go here.
    #
    answer_similarity:
      semantics:
        - "FACE"
      # features:
      #   - "BISYL"
      #   - "HT"

# Default levels to be used for every category unless overridden
DefaultImgWord: &DEFAULT_IMG_WORD
  type: "image_to_word"
  category: "DEFAULT_GROUP"
  name: "Default image to word"

  repetitions: 2
  level: 1
  answers: 1
  points: 50
  sound: true

  filters:
    from_language: "img"
    to_language: "sma"
    semantics: False
    use_category: True

  answer_similarity:
    semantics: False
    use_category: True

DefaultWordImg: &DEFAULT_WORD_IMG
  type: "word_to_image"
  category: "DEFAULT_GROUP"
  name: "Default image to word"

  repetitions: 2
  level: 1
  answers: 1
  points: 50
  sound: true

  filters:
    from_language: "sma"
    to_language: "img"
    semantics: False
    use_category: True

  answer_similarity:
    semantics: False
    use_category: True

# Example question structure if there's a need to override settings to not
# apply to all questions

# AnimalsImgWord: &ANIMALS_IMG_WORD
#   type: "image_to_word"
#   category: "ANIMALS"
#   name: "Animals image to word"
# 
#   repetitions: 2
#   level: 1
#   answers: 1
#   points: 50
#   sound: true
# 
#   filters:
#     from_language: "img"
#     to_language: "sma"
#     semantics:
#       - "ANIMALS"
# 
#   answer_similarity:
#     semantics:
#       - "ANIMALS"
# 
# AnimalsWordImg: &ANIMALS_WORD_IMG
#   type: "word_to_image"
#   category: "ANIMALS"
#   name: "Animals image to word"
# 
#   repetitions: 2
#   level: 1
#   answers: 1
#   points: 50
#   sound: true
# 
#   filters:
#     from_language: "sma"
#     to_language: "img"
#     semantics:
#       - "ANIMALS"
# 
#   answer_similarity:
#     semantics:
#       - "ANIMALS"

# WorldImgWord: &WORLD_IMG_WORD
#   type: "image_to_word"
#   category: "WORLD"
#   name: "World image to word"
# 
#   repetitions: 2
#   level: 1
#   answers: 1
#   points: 50
#   sound: true
# 
#   filters:
#     from_language: "img"
#     to_language: "sma"
#     semantics:
#       - "WORLD"
# 
#   answer_similarity:
#     semantics:
#       - "WORLD"
# 
# WorldWordImg: &WORLD_WORD_IMG
#   type: "word_to_image"
#   category: "WORLD"
#   name: "World image to word"
# 
#   repetitions: 2
#   level: 1
#   answers: 1
#   points: 50
#   sound: true
# 
#   filters:
#     from_language: "sma"
#     to_language: "img"
#     semantics:
#       - "WORLD"
# 
#   answer_similarity:
#     semantics:
#       - "WORLD"

# For category definitions, see categories.yaml.

DefaultQuestions:
  - <<: *DEFAULT_IMG_WORD

  - <<: *DEFAULT_WORD_IMG
    level: 2
    answers: 2
    points: 50

  - <<: *DEFAULT_WORD_IMG
    level: 3
    answers: 3
    points: 50

  - <<: *DEFAULT_WORD_IMG
    level: 4
    answers: 4
    points: 50

Questions:

  # These all come from the default category-- simplifying for now. Leaving as
  # an example of how to override, but ideally overriding questions will be
  # done somewhere else

  # -*- nature-world -*- 

  # - <<: *WORLD_IMG_WORD

  # - <<: *WORLD_WORD_IMG
  #   level: 2
  #   answers: 2
  #   points: 50

  # - <<: *WORLD_WORD_IMG
  #   level: 3
  #   answers: 3
  #   points: 50

  # - <<: *WORLD_WORD_IMG
  #   level: 4
  #   answers: 4
  #   points: 50

  # -*- nature-animals -*- 

  # - <<: *ANIMALS_IMG_WORD

  # - <<: *ANIMALS_WORD_IMG
  #   level: 2
  #   answers: 2
  #   points: 50

  # - <<: *ANIMALS_WORD_IMG
  #   level: 3
  #   answers: 3
  #   points: 50

  # - <<: *ANIMALS_WORD_IMG
  #   level: 4
  #   answers: 4
  #   points: 50

  # -*- test -*-
  - type: "image_to_word"
    category: "TEST"
    name: "Bodypart image to word"

    level: 1
    answers: 1
    points: 50
    sound: true
    repetitions: 1

    filters:
      from_language: "img"
      to_language: "sma"
      semantics:
        - "NUMBER_TEST"

    answer_similarity:
      semantics:
        - "NUMBER_TEST"

  - type: "word_to_image"
    category: "TEST"
    name: "test image to word"

    level: 2
    answers: 3
    points: 50
    sound: true
    repetitions: 0

    filters:
      from_language: "sma"
      to_language: "img"
      semantics:
        - "NUMBER_TEST"

    answer_similarity:
      semantics:
        - "NUMBER_TEST"

  - type: "word_to_image"
    category: "TEST"
    name: "Bodypart image to word"

    level: 3
    answers: 3
    points: 50
    sound: true
    repetitions: 1

    filters:
      from_language: "sma"
      to_language: "img"
      semantics:
        - "ANIMALS"

    answer_similarity:
      semantics:
        - "ANIMALS"

